PrincipalComponents pca = new PrincipalComponents()
...
pca.buildEvaluator(dataSet);
......
pca.getEigenValues()
.....
pca.getUnsortedEigenVectors()
/...
pca.principalComponentsSummary().setMaximumAttributeNames()